<a href="https://colab.research.google.com/github/Chandayadav123/Chandayadav123/blob/main/Linear_regression_multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
df.bedrooms.median()


4.0

In [4]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [6]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [7]:
reg.intercept_


221323.00186540396

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old



In [8]:
reg.predict([[3000, 3, 40]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [9]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384


498408.25157402386

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old



In [10]:
reg.predict([[2500, 4, 5]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

**Machine Learning With Python: Linear Regression Multiple Variables** , Hiring CSV

In [11]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience.mode()


0    eleven
1      five
2     seven
3       ten
4     three
5       two
Name: experience, dtype: object

In [38]:
df.experience = df.experience.fillna(df.experience.mode())
df

experience  test_score  interview_score  salary
0          11         8.0                9   50000
1           5         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [19]:
df = df.rename(columns={'test_score(out of 10)': 'test_score'})
df = df.rename(columns={'interview_score(out of 10)': 'interview_score','salary($)': 'salary'})


In [29]:
text_to_int = {'eleven': 11, 'seven': 7, 'five': 5, 'two': 2, 'ten':10, 'three': 3}
def convert_experience(text):
  try:
    return int(text)  # Try converting to integer first
  except ValueError:
    return text_to_int.get(text)

In [30]:
df['experience'] = df['experience'].apply(convert_experience)


In [31]:
print(df)


   experience  test_score  interview_score  salary
0          11         8.0                9   50000
1           5         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000


In [33]:
df.test_score = df.test_score.fillna(df.test_score.mode())
df

experience  test_score  interview_score  salary
0          11         8.0                9   50000
1           5         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [34]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression()

In [35]:
reg.coef_


array([1023.54746901,  538.56833239,  821.46190215])

In [36]:
reg.intercept_


45380.81648708477

In [37]:
reg.predict([[2, 9, 6]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([57203.79782959])

In [39]:
reg.predict([[12, 10, 10]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([71263.68846074])